services:
  - type: web
    name: cinemaxuz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token
      - key: ADMINS
        value: 5703922034,6764631404
      - key: CHANNELS
        value: @zokirov_muxriddin
      - key: DB_FILE
        value: cinemaxuz.db
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com/webhook
      - key: PORT
        value: 10000
